User nobody
Group nobody

Port 8888

DefaultErrorFile "/usr/share/tinyproxy/default.html"
StatFile "/usr/share/tinyproxy/stats.html"
LogLevel Info

Timeout 600
MaxClients 100
ViaProxyName "tinyproxy"

Allow 127.0.0.1
Allow ::1
Allow 10.155.222.0/24
Allow 10.189.80.0/21
